---
version: "3.7"
services:
  db:
    image: postgres:${POSTGRES_IMAGE_TAG:-16}
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      # mount db creation script in place for bootstrap
      - ./config/db:/docker-entrypoint-initdb.d:ro
    networks:
      - internal

  fhir:
    image: hapiproject/hapi:${FHIR_IMAGE_TAG:-v6.8.3}
    environment:
      spring.datasource.url: jdbc:postgresql://db:5432/hapifhir
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect

      hapi.fhir.bulk_export_enabled: "true"
      hapi.fhir.bulk_import_enabled: "true"
      # TODO remove when cascading delete generally available in FHIR REST API
      hapi.fhir.enforce_referential_integrity_on_delete: "false"
      # allow direct assignment of resource IDs in any format
      hapi.fhir.client_id_strategy: ANY

      hapi.fhir.server_address: https://fhir.${BASE_DOMAIN}/fhir/

      SPRING_CONFIG_LOCATION: file:///opt/application.yaml
    volumes:
      - ./config/fhir/application.yaml:/opt/application.yaml:ro
    depends_on:
      - db
    networks:
      internal:
        aliases:
          - fhir-internal
      ingress:
    labels:
      - traefik.enable=true
      - traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.rule=Host(`fhir.${BASE_DOMAIN}`)
      - traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.fhir-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

      # Hapi does not EXPOSE the ports it listens on, requiring explicit traefik configuration
      - traefik.http.services.fhir-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=8080

  keycloak:
    # use tini as init
    init: true
    image: quay.io/keycloak/keycloak:${KEYCLOAK_IMAGE_TAG:-22.0}
    labels:
      - traefik.enable=true
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.rule=Host(`keycloak.${BASE_DOMAIN}`)
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.keycloak-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt
    command:
      # https://www.keycloak.org/server/importExport#_importing_a_realm_during_startup
      # recent Keycloak releases do not allow importing the master realm on startup; use old properties as workaround
      # https://github.com/keycloak/keycloak/issues/12544#issuecomment-1191846726
      - -Dkeycloak.migration.action=import
      - -Dkeycloak.migration.provider=dir
      - -Dkeycloak.migration.dir=/opt/keycloak/data/import
      - -Dkeycloak.migration.strategy=IGNORE_EXISTING
      - -Dkeycloak.migration.replace-placeholders=true
      - start
      - --log-console-output=json
    environment:
      # https://www.keycloak.org/server/all-config
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres

      # https://www.keycloak.org/server/reverseproxy
      KC_PROXY: edge
      # trust traefik Host header validation
      KC_HOSTNAME_STRICT: "false"

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./config/keycloak/import/:/opt/keycloak/data/import:ro
    depends_on:
      - db
    networks:
      - ingress
      - internal

volumes:
  db-data: {}

networks:
  # internal network for backing services
  internal:

  # ingress network
  ingress:
    external: true
    name: external_web
